=== JohannesPfau/generativePokemonTCG/pokemon_tcg_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "flavorText": {
      "type": "string"
    },
    "types": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "supertype": {
      "type": "string"
    },
    "subtypes": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "level": {
      "type": "string"
    },
    "hp": {
      "type": "string"
    },
    "evolvesFrom": {
      "type": "string"
    },
    "abilities": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "text": {
              "type": "string"
            },
            "type": {
              "type": "string"
            }
          },
          "required": [
            "name",
            "text",
            "type"
          ]
        }
      ]
    },
    "attacks": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "cost": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                },
                {
                  "type": "string"
                },
                {
                  "type": "string"
                }
              ]
            },
            "convertedEnergyCost": {
              "type": "integer"
            },
            "damage": {
              "type": "string"
            },
            "text": {
              "type": "string"
            }
          },
          "required": [
            "name",
            "cost",
            "convertedEnergyCost",
            "damage",
            "text"
          ]
        }
      ]
    },
    "weaknesses": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string"
            },
            "value": {
              "type": "string"
            }
          },
          "required": [
            "type",
            "value"
          ]
        }
      ]
    },
    "retreatCost": {
      "type": "array",
      "items": [
        {
          "type": "string"
        },
        {
          "type": "string"
        },
        {
          "type": "string"
        }
      ]
    },
    "convertedRetreatCost": {
      "type": "integer"
    },
    "number": {
      "type": "string"
    },
    "artist": {
      "type": "string"
    },
    "rarity": {
      "type": "string"
    },
    "nationalPokedexNumbers": {
      "type": "array",
      "items": [
        {
          "type": "integer"
        }
      ]
    },
    "images": {
      "type": "object",
      "properties": {
        "small": {
          "type": "string"
        },
        "large": {
          "type": "string"
        }
      },
      "required": [
        "small",
        "large"
      ]
    }
  },
  "required": [
    "id",
    "name",
    "flavorText",
    "types",
    "supertype",
    "subtypes",
    "level",
    "hp",
    "evolvesFrom",
    "abilities",
    "attacks",
    "weaknesses",
    "retreatCost",
    "convertedRetreatCost",
    "number",
    "artist",
    "rarity",
    "nationalPokedexNumbers",
    "images"
  ]
}

=== JohannesPfau/generativePokemonTCG/example/Ori_3_LLMunion.json
{"id": "aicg2025-1", "name": "Ori", "flavorText": "A small feline predator that scratches everything with his claws, but can purr to calm friends.", "types": ["Darkness"], "supertype": "Pok\u00e9mon", "subtypes": ["Basic"], "level": "28", "hp": "70", "evolvesFrom": "", "abilities": [{"name": "Purring Calm", "text": "Once per turn, when this Pok\u00e9mon is hit by an attack, you may prevent all effects of that attack, including damage.", "type": "Ability"}], "attacks": [{"name": "Clawed Swipe", "cost": ["Colorless", "Colorless", "Darkness"], "convertedEnergyCost": 3, "damage": "60", "text": "Flip a coin. If heads, the Defending Pok\u00e9mon is now Paralyzed."}], "weaknesses": [{"type": "Fighting", "value": "\u00d72"}], "retreatCost": ["Colorless", "Colorless", "Darkness"], "convertedRetreatCost": 3, "number": "1", "artist": "Alexandra Dabrowska", "rarity": "Common", "nationalPokedexNumbers": [123], "images": {"small": "https://images.pokemontcg.io/aicg2025/1.png", "large": "https://images.pokemontcg.io/aicg2025/1_hires.png"}}

=== JohannesPfau/generativePokemonTCG/pokemonData/Politoed.json
{"id": "neo2-8", "name": "Politoed", "flavorText": "Whenever three or more of these get together, they sing in a loud voice that sounds like bellowing.", "types": ["Water"], "supertype": "Pok\u00e9mon", "subtypes": ["Stage 2"], "level": "53", "hp": "100", "evolvesFrom": "Poliwhirl", "abilities": [{"name": "Frog Song", "text": "Whenever Politoed's attack damages the Defending Pok\u00e9mon (after applying Weakness and Resistance), if there are more than 3 Poliwags, Poliwhirls, Poliwraths, and/or Politoeds in play (including your opponent's), that attack does 40 more damage (no matter how many heads you get). This power stops working while Politoed is Asleep, Confused, or Paralyzed.", "type": "Pok\u00e9mon Power"}], "attacks": [{"name": "Doubleslap", "cost": ["Water", "Water", "Colorless", "Colorless"], "convertedEnergyCost": 4, "damage": "40\u00d7", "text": "Flip 2 coins. This attack does 40 damage times the number of heads."}], "weaknesses": [{"type": "Grass", "value": "\u00d72"}], "retreatCost": ["Colorless", "Colorless", "Colorless"], "convertedRetreatCost": 3, "number": "8", "artist": "Tomokazu Komiya", "rarity": "Rare Holo", "nationalPokedexNumbers": [186], "images": {"small": "https://images.pokemontcg.io/neo2/8.png", "large": "https://images.pokemontcg.io/neo2/8_hires.png"}}

=== JohannesPfau/generativePokemonTCG/pokemonData/Abomasnow.json
{"id": "dp2-19", "name": "Abomasnow", "flavorText": "It whips up blizzards in mountains that are always buried in snow. It is the abominable snowman.", "types": ["Grass"], "supertype": "Pok\u00e9mon", "subtypes": ["Stage 1"], "level": "40", "hp": "100", "evolvesFrom": "Snover", "abilities": [{"name": "Glacier Snow", "text": "If Abomasnow is your Active Pok\u00e9mon and is damaged by an opponent's attack (even if Abomasnow is Knocked Out), the Attacking Pok\u00e9mon is now Asleep.", "type": "Pok\u00e9-Body"}], "attacks": [{"name": "Heavy Blizzard", "cost": ["Water", "Colorless", "Colorless"], "convertedEnergyCost": 3, "damage": "60", "text": "Flip a coin. If heads, put 1 damage counter on each of your opponent's Benched Pok\u00e9mon."}], "weaknesses": [{"type": "Fire", "value": "+30"}], "retreatCost": ["Colorless", "Colorless", "Colorless"], "convertedRetreatCost": 3, "number": "19", "artist": "Kazuyuki Kano", "rarity": "Rare", "nationalPokedexNumbers": [460], "images": {"small": "https://images.pokemontcg.io/dp2/19.png", "large": "https://images.pokemontcg.io/dp2/19_hires.png"}}

=== JohannesPfau/generativePokemonTCG/pokemonData/Feraligatr.json
{"id": "neo1-5", "name": "Feraligatr", "flavorText": "It is hard for it to support its own weight out of water, so it gets down on all fours. But it moves fast.", "types": ["Water"], "supertype": "Pok\u00e9mon", "subtypes": ["Stage 2"], "level": "69", "hp": "120", "evolvesFrom": "Croconaw", "abilities": [{"name": "Downpour", "text": "As often as you like during your turn (before your attack), you may discard a Water Energy card from your hand. This power can't be used if Feraligatr is Asleep, Confused, or Paralyzed.", "type": "Pok\u00e9mon Power"}], "attacks": [{"name": "Riptide", "cost": ["Water", "Water", "Water"], "convertedEnergyCost": 3, "damage": "10+", "text": "Does 10 damage plus 10 damage times the number of Water Energy cards in your discard pile. Then, shuffle all Water Energy cards from your discard pile into your deck."}], "weaknesses": [{"type": "Grass", "value": "\u00d72"}], "retreatCost": ["Colorless", "Colorless", "Colorless"], "convertedRetreatCost": 3, "number": "5", "artist": "Ken Sugimori", "rarity": "Rare Holo", "nationalPokedexNumbers": [160], "images": {"small": "https://images.pokemontcg.io/neo1/5.png", "large": "https://images.pokemontcg.io/neo1/5_hires.png"}}

=== JohannesPfau/generativePokemonTCG/pokemonData/Slowbro.json
{"id": "base3-43", "name": "Slowbro", "flavorText": "The Shellder that is latched onto Slowpoke's tail is said to feed on the host's left-over scraps.", "types": ["Psychic"], "supertype": "Pok\u00e9mon", "subtypes": ["Stage 1"], "level": "26", "hp": "60", "evolvesFrom": "Slowpoke", "abilities": [{"name": "Strange Behavior", "text": "As often as you like during your turn (before your attack), you may move 1 damage counter from 1 of your Pok\u00e9mon to Slowbro as long as you don't Knock Out Slowbro. This power can't be used if Slowbro is Asleep, Confused, or Paralyzed.", "type": "Pok\u00e9mon Power"}], "attacks": [{"name": "Psyshock", "cost": ["Psychic", "Psychic"], "convertedEnergyCost": 2, "damage": "20", "text": "Flip a coin. If heads, the Defending Pok\u00e9mon is now Paralyzed."}], "weaknesses": [{"type": "Psychic", "value": "\u00d72"}], "retreatCost": ["Colorless"], "convertedRetreatCost": 1, "number": "43", "artist": "Kagemaru Himeno", "rarity": "Uncommon", "nationalPokedexNumbers": [80], "images": {"small": "https://images.pokemontcg.io/base3/43.png", "large": "https://images.pokemontcg.io/base3/43_hires.png"}}

=== JohannesPfau/generativePokemonTCG/pokemonData/Electrode.json
{"id": "base1-21", "name": "Electrode", "flavorText": "It stores electrical energy under very high pressure. It often explodes with little or no provocation.", "types": ["Lightning"], "supertype": "Pok\u00e9mon", "subtypes": ["Stage 1"], "level": "40", "hp": "80", "evolvesFrom": "Voltorb", "abilities": [{"name": "Buzzap", "text": "At any time during your turn (before your attack), you may Knock Out Electrode and attach it to 1 of your other Pok\u00e9mon. If you do, choose a type of Energy. Electrode is now an Energy card (instead of a Pok\u00e9mon) that provides 2 energy of that type. You can't use this power if Electrode is Asleep, Confused, or Paralyzed.", "type": "Pok\u00e9mon Power"}], "attacks": [{"name": "Electric Shock", "cost": ["Lightning", "Lightning", "Lightning"], "convertedEnergyCost": 3, "damage": "50", "text": "Flip a coin. If tails, Electrode does 10 damage to itself."}], "weaknesses": [{"type": "Fighting", "value": "\u00d72"}], "retreatCost": ["Colorless"], "convertedRetreatCost": 1, "number": "21", "artist": "Keiji Kinebuchi", "rarity": "Rare", "nationalPokedexNumbers": [101], "images": {"small": "https://images.pokemontcg.io/base1/21.png", "large": "https://images.pokemontcg.io/base1/21_hires.png"}}
